# Site settings
title: Roland Jeannier Website
header-img: img/fells_point.jpg
email: rtjeannier@gmail.com
copyright_name: Roland Jeannier
description: "Roland Jeannier is a data scientist with a particular interest in data visualization."
baseurl: ""
url: "http://rolandjeannier.com"
github_username:  rtjeannier

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
